apiVersion: v1
kind: Service
metadata:
  name: rabbit-app
spec:
  selector:
    app: rabbit-app
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 5000
  type: LoadBalancer

